creation of Snapshots for EBS volumes

---
- name: Create EBS volume snapshots
  hosts: localhost
  gather_facts: true

  vars:
    volumes:
      - volume_id: vol-88888
        snapshot_description: "Snapshot for volume 1"
      - volume_id: vol-8888
        snapshot_description: "Snapshot for volume 2"
    ansible_python_interpreter: .....      

  tasks:
    - name: Create EBS volume snapshots
      ec2_snapshot:
        region: us-east-1
        volume_id: "{{ item.volume_id }}"
        description: "{{ item.snapshot_description }}"
      with_items: "{{ volumes }}"
      register: snapshot_result

    - name: Display snapshot IDs
      debug:
        var: item.id
      with_items: "{{ snapshot_result.results }}"  


