---
  - name: Launch EC2 instance with tag "{{ ec2_tag }}"
    ec2: 
      key_name: *****
      instance_type: .....
      image: a:::
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      region: us-east-1
      wait: yes
            #group: webserver
      count: 1
      vpc_subnet_id: ...........
      assign_public_ip: yes
      instance_tags:
        Name: "tagname"
        
      
      
